import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Project: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>我的项目</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Project
