import Head from "next/head";
import Menu from "./Menu";
import styles from "./Layout.module.css";
import { CSSProperties } from "react";

const Layout = (props: { children?: JSX.Element | string; title?: string; icon?: string; head?: JSX.Element; left?: JSX.Element; right?: JSX.Element; leftStyle?: CSSProperties; rightStyle?: CSSProperties; mainStyle?: CSSProperties }) => {
	return (
		<>
			<Menu />
			<div className={styles.container}>
				<Head>
					<title>{props.title ?? "wniko's site"}</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href={props.icon ?? "/favicon.ico"} />
					{props.head}
				</Head>

				<div className={styles.mainContent}>
					<aside className={styles.left} style={props.leftStyle}>
						{props.left}
					</aside>
					<main className={styles.main} style={props.mainStyle}>
						{props.children}
					</main>
					<aside className={styles.right} style={props.rightStyle}>
						{props.right}
					</aside>
				</div>

				<footer className={styles.footer}>123</footer>
			</div>
		</>
	);
};

export default Layout;
