import Head from "next/head";
import Menu from "./Menu";
import styles from "./Layout.module.css";

const Layout = (props: {
  children?: JSX.Element | string;
  title?: string;
  icon?: string;
  head?: JSX.Element;
}) => {
  return (
    <>
      <Menu />
      <div className={styles.container}>
        <Head>
          <title>{props.title ?? "wniko's site"}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href={props.icon ?? "/favicon.ico"} />
          {props.head}
        </Head>

        <main className={styles.main}>{props.children}</main>

        <footer className={styles.footer}>
            123
        </footer>
      </div>
    </>
  );
};

export default Layout;
